const {
  NODE_ENV,
  VITE_SKIP_A11Y,
  UNDER_TEST,
  FLATPAK_ID,
  VITE_DEBUG_VERBOSE,
  PUBLIC_URL,
  VITE_HEADLAMP_VERSION,
  VITE_HEADLAMP_GIT_VERSION,
  VITE_HEADLAMP_PRODUCT_NAME,
  VITE_HEADLAMP_BACKEND_TOKEN,
} = import.meta.env;

const env = {
  NODE_ENV,
  VITE_SKIP_A11Y,
  UNDER_TEST,
  FLATPAK_ID,
  VITE_DEBUG_VERBOSE,
  PUBLIC_URL,
  VITE_HEADLAMP_VERSION,
  VITE_HEADLAMP_GIT_VERSION,
  VITE_HEADLAMP_PRODUCT_NAME,
  VITE_HEADLAMP_BACKEND_TOKEN,
};

export default env;
