name: Build release artifact

on:
  push:
    branches:
      - rc-*
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: App linux
      run: |
        make app-linux
    - name: Rename AppImage 64bit version
      run: |
        FILE_PATH=$(echo app/dist/Headlamp*x86_64*.AppImage) mv ${FILE_PATH} $(echo ${FILE_PATH}|sed s/x86_64/x64/)
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./app/dist/Headlamp*.*
        if-no-files-found: error
        retention-days: 1
  build-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Dependencies
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install make
    - name: App Windows
      run: |
        npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
        make app-win
    - name: Rename Win exec to include arch
      run: |
        FILE_PATH=$(echo app/dist/Headlamp*win*.exe) mv ${FILE_PATH} $(echo ${FILE_PATH}|sed s/win/win-x64/)
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./app/dist/Headlamp*.*
        if-no-files-found: error
        retention-days: 1
  build-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Dependencies
      run: brew install make
    - name: App Mac
      run: |
        make app-mac
    - name: Rename Mac 64bit to include arch
      run: |
        FILE_PATH=$(echo app/dist/Headlamp*mac.exe) mv ${FILE_PATH} $(echo ${FILE_PATH}|sed s/mac/mac-x64/)
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./app/dist/Headlamp*.*
        if-no-files-found: error
        retention-days: 1
