name: Trigger Flatpak Headlamp version update

# See https://github.com/flathub/io.kinvolk.Headlamp
on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger_flatpak_update:
    name: Trigger Flatpak Headlamp version update
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Trigger via gh
        env:
          GITHUB_TOKEN: ${{ secrets.FLATPAK_HEADLAMP_REPO_TOKEN }}
        run: |
          gh api repos/flathub/io.kinvolk.Headlamp/dispatches --raw-field event_type=headlamp-release
